/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ims.gui;

import ims.bll.EmployeeBLL;
import ims.model.Employee;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.SessionFactory;

/**
 *
 * @author NAT
 */
public class EmployeeList extends javax.swing.JFrame {
    
    List<Employee> listEmp = new ArrayList<Employee>();
    EmployeeBLL employeeBLL;
    private SessionFactory factory;

    /** Creates new form EmployeeList */
    public EmployeeList() {
        initComponents();
        setInfoDialog();
        employeeBLL = new EmployeeBLL();
        formWindowOpened();
        
    }
    public  void setInfoDialog() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - getHeight()) / 2);
        setLocation(x, y);        
        setResizable(false);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btNew = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmp = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);

        btNew.setText("Thêm ");
        btNew.setFocusable(false);
        btNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btNew);
        jToolBar1.add(jSeparator1);

        jButton2.setText("Sửa");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator2);

        jButton3.setText("Xóa");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);
        jToolBar1.add(jSeparator3);

        jButton4.setText("In");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator4);

        jButton5.setText("Thoát");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton5);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 25));

        tbEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Họ", "Tên", "Mã chấm công", "Giới tính", "Ngày sinh", "Nơi sinh", "Nguyên quán"
            }
        ));
        jScrollPane1.setViewportView(tbEmp);
        if (tbEmp.getColumnModel().getColumnCount() > 0) {
            tbEmp.getColumnModel().getColumn(0).setPreferredWidth(100);
            tbEmp.getColumnModel().getColumn(1).setPreferredWidth(200);
            tbEmp.getColumnModel().getColumn(2).setPreferredWidth(100);
            tbEmp.getColumnModel().getColumn(3).setPreferredWidth(100);
            tbEmp.getColumnModel().getColumn(4).setPreferredWidth(80);
            tbEmp.getColumnModel().getColumn(5).setPreferredWidth(100);
            tbEmp.getColumnModel().getColumn(6).setPreferredWidth(150);
            tbEmp.getColumnModel().getColumn(7).setPreferredWidth(150);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 830, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewActionPerformed
        EmployeeInfo emGui= new EmployeeInfo(this);
        emGui.setTitle("Thêm nhân viên");
        emGui.setVisible(true);
        
        Employee newEmployee = emGui.getEmployee();

        if (newEmployee != null) {
//            System.out.println(newEmployee.getChuyennganh().getMaTrinhdo().getTrinhdo());
            try {
                employeeBLL.save(newEmployee);
                listEmp.add(newEmployee);
                
                DefaultTableModel model = (DefaultTableModel) tbEmp.getModel();
                int newRow = tbEmp.getRowCount();
                model.addRow(new Object[0]);
                updateTableEmployee(newEmployee, newRow);
                
            } catch (Exception ex) {
                String message = "Could not save new employee. Error:\n" + ex.getMessage();
                JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
        }
    }//GEN-LAST:event_btNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeList().setVisible(true);
            }
        });
    }

    private void formWindowOpened(){
        try {
            listEmp = employeeBLL.getAll();
            DefaultTableModel model = (DefaultTableModel) tbEmp.getModel();
            int row = 0;
            for (Iterator iterator = listEmp.iterator(); iterator.hasNext();) {
                Employee emp = (Employee) iterator.next();
                model.addRow(new Object[0]);
                updateTableEmployee(emp, row);
                row++;
            }
        } catch (Exception ex) {
            Logger.getLogger(EmployeeList.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNew;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tbEmp;
    // End of variables declaration//GEN-END:variables

    public void updateTableEmployee(Employee emp, int row) {

        DefaultTableModel model = (DefaultTableModel) tbEmp.getModel();
        model.setValueAt(emp.getMaNv(), row, 0);
        model.setValueAt(emp.getTenHoDem(), row, 1);
        model.setValueAt(emp.getTen(), row, 2);
        model.setValueAt(emp.getMaChamcong(), row, 3);
        model.setValueAt((emp.getSex()==true?"Nam":"Nữ"), row, 4);
        model.setValueAt(emp.getNgaySinh(), row, 5);
        model.setValueAt(emp.getNoisinh(), row, 6);
        model.setValueAt(emp.getNguyenquan().getTentinhthanh(), row, 7);
    }

}
