/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ims.gui;

import ims.bll.EmployeeBLL;
import ims.bll.FormatDate;
import ims.model.Employee;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.Format;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.SessionFactory;

/**
 *
 * @author NAT
 */
public class EmployeeList extends javax.swing.JFrame {
    
    List<Employee> listEmp = new ArrayList<Employee>();
    EmployeeBLL employeeBLL;
    private SessionFactory factory;
    Employee empForEdit;
    

    /** Creates new form EmployeeList */
    public EmployeeList() {
        initComponents();
        setInfoDialog();
        employeeBLL = new EmployeeBLL();
        formWindowOpened();
        
    }
    public  void setInfoDialog() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - getHeight()) / 2);
        setLocation(x, y);        
        setResizable(false);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btNew = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnEditEmp = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnDelete = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnShow = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmp = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);

        btNew.setText("Thêm ");
        btNew.setFocusable(false);
        btNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btNew);
        jToolBar1.add(jSeparator1);

        btnEditEmp.setText("Sửa");
        btnEditEmp.setFocusable(false);
        btnEditEmp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditEmp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditEmpActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditEmp);
        jToolBar1.add(jSeparator2);

        btnDelete.setText("Xóa");
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDelete);
        jToolBar1.add(jSeparator3);

        btnShow.setText("In");
        btnShow.setFocusable(false);
        btnShow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnShow.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });
        jToolBar1.add(btnShow);
        jToolBar1.add(jSeparator4);

        btnExit.setText("Thoát");
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnExit);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 25));

        tbEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Họ", "Tên", "Mã chấm công", "Giới tính", "Ngày sinh", "Nơi sinh", "Nguyên quán"
            }
        ));
        jScrollPane1.setViewportView(tbEmp);
        if (tbEmp.getColumnModel().getColumnCount() > 0) {
            tbEmp.getColumnModel().getColumn(0).setPreferredWidth(100);
            tbEmp.getColumnModel().getColumn(1).setPreferredWidth(200);
            tbEmp.getColumnModel().getColumn(2).setPreferredWidth(100);
            tbEmp.getColumnModel().getColumn(3).setPreferredWidth(100);
            tbEmp.getColumnModel().getColumn(4).setPreferredWidth(80);
            tbEmp.getColumnModel().getColumn(5).setPreferredWidth(100);
            tbEmp.getColumnModel().getColumn(6).setPreferredWidth(150);
            tbEmp.getColumnModel().getColumn(7).setPreferredWidth(150);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 830, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewActionPerformed
        EmployeeInfo emGui= new EmployeeInfo(this);
        emGui.setTitle("Thêm nhân viên");
        emGui.setVisible(true);
        
        Employee newEmployee = emGui.getEmployee();

        if (newEmployee != null) {
            System.out.println(newEmployee.getChuyennganh().getMaTrinhdo().getTrinhdo());
            try {
                employeeBLL.save(newEmployee);
                listEmp.add(newEmployee);
                
                DefaultTableModel model = (DefaultTableModel) tbEmp.getModel();
                int newRow = tbEmp.getRowCount();
                model.addRow(new Object[0]);
                updateTableEmployee(newEmployee, newRow);
                
            } catch (Exception ex) {
                try {
                    employeeBLL.closeSession();
                } catch (Exception ex1) {
                    JOptionPane.showMessageDialog(this, ex1, "Error", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(EmployeeList.class.getName()).log(Level.SEVERE, null, ex1);
                }
                String message = "Could not save new employee. Error:\n" + ex.getMessage();
                JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            System.out.println("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
        }
    }//GEN-LAST:event_btNewActionPerformed

    private void btnEditEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditEmpActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbEmp.getSelectedRow();
        EmployeeInfo emGui = new EmployeeInfo(this);
        if(selectedRow >= 0){
            empForEdit = listEmp.get(selectedRow);
            emGui.setEmployee(empForEdit);
            emGui.setContentToEdit();
            emGui.setVisible(true);
        }
        
        Employee editedEmployee = emGui.getEmployee();

            
	if (editedEmployee != null) {
            try {
                employeeBLL.update(editedEmployee);		
                updateTableEmployee(editedEmployee,selectedRow);                                
            } catch (Exception ex) {
                try {
                    employeeBLL.closeSession();
                } catch (Exception ex1) {
                    JOptionPane.showMessageDialog(this, ex1, "Error", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(EmployeeList.class.getName()).log(Level.SEVERE, null, ex1);
                }
                String message = "Could not update Employee. Error:\n" + ex.getMessage();
                JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);			
            }				
        }
    }//GEN-LAST:event_btnEditEmpActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        // TODO add your handling code here:
        formWindowOpened();
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbEmp.getSelectedRow();
        Employee empForDelete;
        if(selectedRow >= 0){
            empForDelete = listEmp.get(selectedRow);
            if (empForDelete != null) {
                    try{
                        String message = String.format( "Xoa '%s'?", empForDelete.toString()); 
                        int answer = JOptionPane.showConfirmDialog(this, message, "Xac nhan", JOptionPane.YES_NO_OPTION);
                        if (answer == JOptionPane.OK_OPTION) {                                
                            employeeBLL.delete(empForDelete);
                            listEmp.remove(empForDelete);
                            updateTableEmployee(selectedRow);
                        }
                    }catch(Exception e){
                        try {
                            employeeBLL.closeSession();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(this, ex, "Error", JOptionPane.ERROR_MESSAGE);
                            Logger.getLogger(EmployeeList.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
        }				
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeList().setVisible(true);
            }
        });
    }

    private void formWindowOpened(){
        
        
        try {
            listEmp = employeeBLL.getAll();
            DefaultTableModel model = (DefaultTableModel) tbEmp.getModel();
            model.setRowCount(0);
            int row = 0;
            for (Iterator iterator = listEmp.iterator(); iterator.hasNext();) {
                Employee emp = (Employee) iterator.next();
                model.addRow(new Object[0]);
                updateTableEmployee(emp, row);
                row++;
            }
        } catch (Exception ex) {
            try {
                employeeBLL.closeSession();
            } catch (Exception ex1) {
                JOptionPane.showMessageDialog(this, ex1, "Error", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(EmployeeList.class.getName()).log(Level.SEVERE, null, ex1);
            }
            Logger.getLogger(EmployeeList.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNew;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEditEmp;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnShow;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tbEmp;
    // End of variables declaration//GEN-END:variables

    public void updateTableEmployee(Employee emp, int row) {

//        Format formatter = new SimpleDateFormat("dd-MM-yyyy");
//        String s = formatter.format(emp.getNgaySinh().toString());
        DefaultTableModel model = (DefaultTableModel) tbEmp.getModel();
        model.setValueAt(emp.getMaNv(), row, 0);
        model.setValueAt(emp.getTenHoDem(), row, 1);
        model.setValueAt(emp.getTen(), row, 2);
        model.setValueAt(emp.getMaChamcong(), row, 3);
        model.setValueAt((emp.getSex()==true?"Nam":"Nữ"), row, 4);
        model.setValueAt((emp.getNgaySinh() == null? null :emp.getNgaySinh().toString()), row, 5);
        model.setValueAt(emp.getNoisinh(), row, 6);
        model.setValueAt(emp.getNguyenquan().getTentinhthanh(), row, 7);
    }

    private void updateTableEmployee(int selectedRow) {
        DefaultTableModel model = (DefaultTableModel) tbEmp.getModel();
        model.removeRow(selectedRow);
    }

}
